
<title>Phương thức xét tuyển 4</title>

<div class="content pb-5">
    <h3 style="color: #a21010;" align="center">PHƯƠNG THỨC 4: Xét vào ngành Sư phạm bằng điểm học bạ THPT</h3>
    <p class="MsoNormal" style="text-align: justify; text-indent: 0pt; line-height: normal; margin: 6.0pt 0cm;"><span style="font-family: Arial;"><span lang="SV">Xét tuyển dựa vào Điểm trung bình môn 6 học kỳ &nbsp;của 3 môn trong tổ hợp xét tuyển ứng với ngành do thí sinh đăng ký. Điểm mỗi môn (gọi là <b>Điểm M</b>) để tính điểm xét tuyển được tính bằng trung bình cộng của điểm trung bình môn trong 6 học kỳ <i>(làm tròn đến hai chữ số thập phân)</i>, công thức tính <b>Điểm M</b> như sau:</span></span></p>
    <p class="MsoNormal" style="text-align: center; text-indent: 0pt; line-height: normal; margin: 6.0pt 0cm;"><img src="../images/phuongthuc4_ct.PNG" alt="" width="682" height="65">&nbsp;</p>
    <p class="MsoNormal" style="text-align: justify; text-indent: 36.0pt; line-height: normal; margin: 3.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><i><span lang="EN-US">Trong đó: ĐTBM<sub>HK</sub>&nbsp; là Điểm trung bình môn học kỳ (HK1L10: Học kỳ 1 Lớp 10)</span></i></span></p>
    <p class="MsoNormal" style="text-align: justify; text-indent: 0pt; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;">Riêng ngành <b>Giáo dục thể chất</b>, thí sinh phải dự thi môn Năng khiếu TDTT do Trường ĐHCT tổ chức thi để lấy điểm (thời gian thi thông báo sau).</span></span></p>
    <p><strong>* Ngành xét tuyển</strong></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;"> - 13 ngành đào tạo giáo viên (xem <a class="site-link" href="/NLN_MT/views/TT-tuyen-sinh/">Danh mục ngành tuyển sinh đại học chính quy năm 2022</a>). </span> </span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;">- <span lang="SV">Chỉ tiêu xét tuyển: tối đa 40% chỉ tiêu của ngành tương ứng.</span></span></p>
    <p><strong>* Đối tượng</strong></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;"> Thí sinh tốt nghiệp THPT từ năm 2022 về trước</span></span></p>
    <p><strong>* Điều kiện đăng ký xét tuyển</strong></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;"> Thí sinh đạt điều kiện dưới đây được đăng ký xét tuyển</span></span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;">- Đối với ngành Giáo dục thể chất: Học lực cả năm lớp 12 được xếp loại khá trở lên; Những trường hợp sau đây chỉ yêu cầu học lực cả năm lớp 12 xếp loại trung bình trở lên:</span></span></p>
    <p class="MsoListParagraphCxSpFirst" style="text-align: justify; text-indent: -18.0pt; line-height: normal; margin: 6.0pt 0cm .0001pt 49.65pt;"><span lang="EN-US" style="font-style: normal; font-variant: normal; font-weight: normal; font-family: Arial; color: black;"> +&nbsp;&nbsp; </span><span style="font-family: Arial;"><span lang="EN-US" style="color: black;">Thí sinh là vận động viên cấp 1, kiện tướng, vận động viên đã từng đoạt huy chương tại Hội khỏe Phù Đổng, các giải trẻ quốc gia và quốc tế hoặc giải vô địch quốc gia và quốc tế.</span></span></p>
    <p class="MsoListParagraphCxSpLast" style="text-align: justify; text-indent: -18.0pt; line-height: normal; margin: 6.0pt 0cm .0001pt 49.65pt;"><span lang="EN-US" style="font-style: normal; font-variant: normal; font-weight: normal; font-family: Arial; color: black;"> +&nbsp;&nbsp; </span><span style="font-family: Arial;"><span lang="EN-US" style="color: black;">Thí sinh có điểm thi môn Năng khiếu TDTT (do Trường ĐHCT tổ chức thi) từ 9,0 trở lên (theo thang điểm 10).</span></span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span lang="en-us"><span style="font-family: Arial;">-</span></span><span style="font-family: Arial;"><span lang="EN-US" style="color: black;"> Đối với những ngành sư phạm khác: Học lực cả năm lớp 12 được xếp loại GIỎI.</span></span></p>
    <p><strong>* Điểm xét tuyển</strong></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;"> Là tổng điểm 3 môn theo tổ hợp xét tuyển, cộng với điểm ưu tiên (đối tượng ưu tiên, khu vực ưu tiên theo quy định của Quy chế tuyển sinh). Không nhân hệ số và tính theo công thức: </span></span></p>
    <p class="MsoNormal" style="text-align: center; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ĐXT = (ĐiểmM1 + ĐiểmM2 + ĐiểmM3) + Điểm ưu tiên</span></span></p>
    <p><strong>* Nguyên tắc xét tuyển</strong></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;">+ Thí sinh được đăng ký tối đa 03 nguyện vọng và phải xếp theo thứ tự ưu tiên từ cao xuống thấp (ưu tiên 1 là nguyện vọng cao nhất). Đối với từng ngành, các thí sinh được xét tuyển bình đẳng theo điểm xét tuyển và không phân biệt thứ tự ưu tiên. Xét theo điểm từ cao xuống thấp.</span></span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;">+ Đối với mỗi thí sinh, tất cả các nguyện vọng đều được xét tuyển và chỉ trúng tuyển vào 1 nguyện vọng có ưu tiên cao nhất trong số các nguyện vọng đủ điều kiện trúng tuyển.</span></span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span style="font-family: Arial;"><span lang="EN-US" style="color: black;">+ Điểm trúng tuyển giữa các tổ hợp xét tuyển trong cùng 1 ngành là bằng nhau và được xác định theo ngành. Đây chính là điểm xét tuyển của thí sinh cuối cùng trong danh sách trúng tuyển và gọi là Điểm chuẩn trúng tuyển của ngành.</span></span></p>
    <p><strong>* Thời gian và hồ sơ đăng ký</strong></p>
    <p class="MsoNormal" style="color: #222222; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify; line-height: normal; font-family: Arial; background-color: #ffffff; margin: 6pt 0cm 0cm 0cm;"><span lang="SV">Từ ngày 05/05/2022 đến hết ngày 15/6/2022</span></p>
    <p class="MsoNormal" style="color: #222222; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify; line-height: normal; font-family: Arial; background-color: #ffffff; margin: 6pt 0cm 0cm 0cm;"><b><span style="color: black;">Bước 1:</span></b><span style="color: black;">&nbsp;Đăng ký trực tuyến tại website&nbsp;</span><a style="color: blue;" href="http://xettuyen.ctu.edu.vn/" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://xettuyen.ctu.edu.vn&amp;source=gmail&amp;ust=1614354097710000&amp;usg=AFQjCNFk_jDIruM6H8PD0gdjwr8MC-01dg">http://xettuyen.ctu.edu.vn</a><span style="color: black;">&nbsp;&nbsp;</span><span style="color: #c00000;">(để tránh mọi sai sót, thí sinh cần đọc kỹ các nội dung hướng dẫn trên hệ thống trước khi đăng ký)</span><span style="color: black;">.</span></p>
    <p class="MsoNormal" style="color: #222222; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: justify; line-height: normal; font-family: Arial; background-color: #ffffff; margin: 6pt 0cm 0cm 0cm;"><b><span style="color: black;">Bước 2:</span></b><span style="color: black;">&nbsp;Sau khi đăng ký trực tuyến&nbsp;<b>và chắc chắn không còn chỉnh sửa</b>, thí sinh gửi hồ sơ về Trường gồm có:</span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span lang="SV">- </span><span style="color: black;">Phiếu</span><span lang="SV"> đăng ký xét tuyển (<i>in từ hệ thống đăng ký trực tuyến của Trường</i>);</span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span lang="SV">- 01 bản </span><span style="color: black;">photo</span><span lang="SV"> Học bạ hoặc</span> Giấy xác nhận kết quả học tập THPT <i>(đủ 6 học kỳ xét)</i><span lang="SV">;</span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;">- Đối với thí sinh đã tốt nghiệp THPT từ năm 2021 trở về trước thì nộp thêm 01 bản photo Bằng tốt nghiệp THPT (không công chứng) hoặc Bản gốc Giấy chứng nhận tốt nghiệp THPT tạm thời</p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span lang="SV">- Đối với thí </span><span style="color: black;">sinh</span><span lang="SV"> học lực trung bình đăng ký vào ngành Giáo dục thể chất: nếu là vận động viên cấp 1, kiện tướng, vận động viên đã từng đoạt huy chương tại Hội khỏe Phù Đổng, các giải trẻ quốc gia và quốc tế hoặc giải vô địch quốc gia và quốc tế thì nộp thêm bản photo giấy chứng nhận có liên quan đến thành tích trên.</span></p>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;"><span lang="SV">- Phí </span><span style="color: black;">đăng</span><span lang="SV"> ký: 30.000đ/ 1 nguyện vọng</span></p>
    <p class="MsoNormal" style="margin-bottom: .0001pt; line-height: normal;"><span style="font-family: Arial;"><b> <span lang="EN-US" style="color: #333333; background: white;"> Bước 3: Gửi hồ sơ về Trường ĐHCT&nbsp;</span></b></span></p>
    <p class="MsoNormal" style="margin-bottom: .0001pt; line-height: normal;"><span style="font-family: Arial;"><b> <span lang="EN-US" style="color: #333333; background: white;"> Thí sinh chọn 1 trong 2 cách dưới đây để nộp hồ sơ xét tuyển và phí đăng ký cho Trường ĐHCT:&nbsp;</span></b></span></p>
    <p class="MsoNormal" style="line-height: normal; vertical-align: middle; margin-bottom: .0001pt; background: white;"><span style="font-family: Arial;"><b><u> <span lang="EN-US" style="color: #333333; background: white;"> CÁCH 1:</span></u><span lang="EN-US" style="color: #333333; background: white;"> Nộp </span><span lang="EN-US" style="color: #333333;">trực tiếp tại PHÒNG ĐÀO TẠO</span></b><span lang="EN-US" style="color: #333333;"> <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Địa chỉ: Khu II, Đường 3/2, P. Xuân Khánh, Q. Ninh Kiều, TP. Cần Thơ<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thời gian nhận hồ sơ: Tất cả các ngày từ 5/5 đến 15/6/2022 (Kể cả Thứ 7 và Chủ nhật)<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;- Sáng từ 7 giờ 00 đến 11 giờ 00<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;- Chiều từ 13 giờ 00 đến 17 giờ 00<br> <b><u><span style="background: white;">CÁCH 2:</span></u><span style="background: white;"> &nbsp;Sử dụng dịch vụ GỬI HỒ SƠ XÉT TUYỂN CỦA BƯU ĐIỆN VIỆT NAM</span></b></span></span></p>
    <p class="MsoNormal" style="margin-bottom: .0001pt; line-height: normal;" align="center"><img src="../images/pt34_nophoso1.PNG" width="430" height="83" border="0"></p>
    <p class="MsoListParagraphCxSpFirst" style="line-height: normal; vertical-align: middle; background: white;"><span style="font-family: Arial;"><span lang="EN-US" style="color: #333333;">1. Thí sinh mang đầy đủ hồ sơ xét tuyển và phí đăng ký đến Bưu cục giao dịch của BƯU ĐIỆN VIỆT NAM (hoặc điểm Bưu điện văn hóa xã) để gửi chuyển phát HSXT và Phí đăng ký về Trường Đại học Cần Thơ (<b>theo mã Trường TCT</b>). <i>Thí sinh có thể tra cứu tìm địa chỉ của bưu cục gần nơi ở của thí sinh tại website</i></span><i><u><span lang="EN-US" style="color: #337AB7;"><a href="http://www.vnpost.vn/vi-vn/buu-cuc/tim-kiem" target="_blank"><span style="color: #337ab7;"> http://www.vnpost.vn/vi-vn/buu-cuc/tim-kiem</span></a></span></u></i></span></p>
    <p class="MsoListParagraphCxSpFirst" style="line-height: normal; vertical-align: middle; background: white;"><span style="font-family: Arial;"><span lang="EN-US" style="color: #333333;">2. Khi hoàn</span> <span lang="EN-US" style="color: #333333;">tất thủ tục nhận, giao dịch viên ở Bưu cục sẽ giao cho thí sinh&nbsp;<b>01 Vận đơn</b>, trên đó có&nbsp;<b>Mã bưu gửi</b>. Thí sinh phải&nbsp;<b>giữ gìn cẩn thận</b>&nbsp;Vận đơn này để đối chiếu khi cần thiết (Xem hình minh họa)</span></span></p>
    <p class="MsoListParagraphCxSpFirst" style="line-height: normal; vertical-align: middle; background: white;" align="center"><img src="../images/pt34_nophoso2.PNG" width="488" height="126" border="0"></p>
    <p class="MsoListParagraphCxSpLast" style="line-height: normal; vertical-align: middle; background: white;"><span style="font-family: Arial;"> <span style="color: #333333; font-weight: bold;">3. Một số lưu ý:</span></span></p>
    <ul style="margin-bottom: 0cm;" type="disc">
        <ul style="margin-bottom: 0cm;" type="circle">
            <li class="MsoNormal" style="color: #333333; line-height: normal; vertical-align: middle; background: white;"><span style="font-family: Arial;"><b><span lang="EN-US">Địa chỉ nơi nhận:</span></b><span lang="EN-US">&nbsp;PHÒNG ĐÀO TẠO – TRƯỜNG ĐẠI HỌC CẦN THƠ<br> Khu II, Đường 3/2, P. Xuân Khánh, Q. Ninh Kiều, TP. Cần Thơ</span></span></li>
            <li class="MsoNormal" style="color: #333333; line-height: normal; vertical-align: middle; background: white;"><span style="font-family: Arial;"><b><span lang="EN-US">Ghi họ tên</span></b><span lang="EN-US">, số điện thoại di động, số CMND của thí sinh ngoài bì thư để liên lạc khi cần thiết.</span></span></li>
            <li class="MsoNormal" style="color: #333333; line-height: normal; vertical-align: middle; background: white;"><span style="font-family: Arial;"><span lang="EN-US">Sau khi Trường ĐHCT nhận được Hồ sơ của thí sinh, Trường sẽ cập nhật tình trạng hồ sơ và thí sinh có thể kiểm tra được trong menu “Hồ sơ của tôi” trên hệ thống Đăng ký.</span></span></li>
            <li class="MsoNormal" style="color: #333333; line-height: normal; vertical-align: middle; background: white;"><span style="font-family: Arial;"><span lang="EN-US">Muốn biết hồ sơ của mình đã được vận chuyển đến Trường ĐHCT hay chưa, thí sinh có thể tra cứu bưu phẩm tại website&nbsp;</span><u><span lang="EN-US" style="color: #337AB7;"><a href="http://www.vnpost.vn/" target="_blank"><span style="color: #337ab7;">http://www.vnpost.vn/</span></a></span></u><span lang="EN-US"> &nbsp;(sử dụng “Mã bưu gửi” trên Vận đơn để “Tra cứu - định vị” bưu phẩm)</span></span></li>
        </ul>
    </ul>
    <p class="MsoNormal" style="text-align: justify; line-height: normal; margin: 6.0pt 0cm .0001pt 0cm;">&nbsp;</p>
    <p>&nbsp;</p>
</div>

<?php
require_once "../../../partial/tail.php"
?>